# Generated by Django 2.2 on 2021-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='userbtcaddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BTC Address'),
        ),
    ]
