# Generated by Django 2.2 on 2021-10-06 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_currency', '0005_auto_20210702_1917'),
        ('trade_auth', '0002_useraddress_userbtcaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Currency', to='trade_currency.TradeCurrency', verbose_name='Currency')),
                ('useraddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwalletaddress', to='trade_auth.UserAddress', verbose_name='Address')),
            ],
            options={
                'verbose_name': 'UserWallet',
                'db_table': 'p2Gw2fGKotK7NcaN',
            },
        ),
    ]
