# Generated by Django 2.2 on 2020-06-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country Name')),
                ('iso3', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO3')),
                ('iso2', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO2')),
                ('phone_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Phone Code')),
                ('capital', models.CharField(blank=True, max_length=30, null=True, verbose_name='Capital Name')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Currency')),
                ('native', models.CharField(blank=True, max_length=10, null=True, verbose_name='Native')),
                ('emoji', models.CharField(blank=True, max_length=30, null=True, verbose_name='emoji')),
                ('emojiU', models.CharField(blank=True, max_length=30, null=True, verbose_name='emojiU')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='State Name')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='State Code')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_list', to='locations.Country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City Name')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('state_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='State Code')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, null=True, verbose_name='Longitude')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_countries_list', to='locations.Country')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_state_list', to='locations.State')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
