# Generated by Django 2.2 on 2020-06-22 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='flas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='wikiDataId',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='wikiDataId'),
        ),
    ]
