# Generated by Django 2.2 on 2020-06-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200622_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='fips_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Flip Code'),
        ),
        migrations.AddField(
            model_name='state',
            name='iso2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO2'),
        ),
    ]
