# Generated by Django 2.2 on 2020-12-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200622_1452'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='6XusFR73xm2pnpub',
        ),
        migrations.AlterModelTable(
            name='country',
            table='ahkC7SJqOdgcUxhp',
        ),
        migrations.AlterModelTable(
            name='state',
            table='jyahYj2ZKtBRbUOm',
        ),
    ]
