# Generated by Django 2.2 on 2021-05-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20201228_1927'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cities',
            table='aB238pPacUxQduGK',
        ),
        migrations.AlterModelTable(
            name='country',
            table='YUE90HH8WIZY76Tm',
        ),
        migrations.AlterModelTable(
            name='state',
            table='bBTLVprWaUrBQRnZ',
        ),
    ]
