# Generated by Django 2.2 on 2021-08-26 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HotBitDeal', max_length=50, verbose_name='Site Name')),
                ('caption', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Site Caption')),
                ('director', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Director')),
                ('reg_info', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Site Registration Info')),
                ('address1', models.CharField(max_length=100, verbose_name='Contact Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code')),
                ('phone1', models.CharField(blank=True, help_text='Phone number Format : 0xxxxxxxxxx', max_length=13, null=True, verbose_name='Phone Number')),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='Site Logo')),
                ('company_fav', models.ImageField(blank=True, null=True, upload_to='favicons', verbose_name='Site Favicon')),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True, verbose_name='Copy Rights')),
                ('admin_redirect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Admin Redirect')),
                ('fb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'CMRaaNrAUFW1I04S',
            },
        ),
        migrations.CreateModel(
            name='Company_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_maintenance_status', models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='Site Maintenance')),
                ('site_maintenance', models.TextField(blank=True, null=True)),
                ('adminipaddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Admin IP Address')),
                ('company_settings_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='company.Company')),
            ],
            options={
                'verbose_name': 'CompanySetting',
                'verbose_name_plural': 'CompanySetting',
                'db_table': 'cX0ZvTLd47wUtoWT',
            },
        ),
    ]
