# Generated by Django 2.2 on 2022-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_settings',
            name='IOS_site_maintenance_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='IOS Site Maintenance'),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='site_maintenance_status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Under Maintenance')], default=1, verbose_name='Android Site Maintenance'),
        ),
    ]
