# Generated by Django 2.2 on 2022-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220915_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Android_version',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Android Version'),
        ),
        migrations.AddField(
            model_name='company',
            name='IOS_version',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IOS Version'),
        ),
    ]
