# Generated by Django 2.2 on 2021-06-17 14:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('message', models.TextField(help_text='Message', verbose_name='Message')),
                ('reply', models.TextField(blank=True, help_text='Message', null=True, verbose_name='Reply')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('read_status', models.IntegerField(choices=[(0, 'UnReply'), (1, 'Replied')], default=0, verbose_name='Read Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contactus',
                'db_table': 'cSlmuii55R4oLi9Q',
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('year', models.CharField(max_length=50, verbose_name='Year')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roadmap',
                'db_table': 'RQ99aE1KxKWQ2o1D',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faq',
                'db_table': 'fOfwvYRmmHVwm48s',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('Subject', models.CharField(max_length=300, verbose_name='Subject')),
                ('content', ckeditor.fields.RichTextField(help_text='Content', verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplate_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplate_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EmailTemplate',
                'db_table': 'E5w4yMqjVXoTQlty',
            },
        ),
        migrations.CreateModel(
            name='Currencylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('softcap', models.CharField(max_length=50, verbose_name='Soft cap')),
                ('hardcap', models.CharField(max_length=50, verbose_name='Hard cap')),
                ('attachement', models.FileField(blank=True, null=True, upload_to='', verbose_name='WhitePaper')),
                ('timer_date', models.DateTimeField()),
                ('buytoken_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buy Token Url')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencylist_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencylist_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currencylist',
                'db_table': 'c2plLP6av1pk3STI',
            },
        ),
        migrations.CreateModel(
            name='Cms_StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('contenttype', models.IntegerField(choices=[(0, 'page'), (1, 'content')], default=0, verbose_name='Content')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_staticcontent_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_staticcontent_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cms_StaticContent',
                'db_table': 'C9bDIAkN3dlB5T1b',
            },
        ),
        migrations.CreateModel(
            name='Blockip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockip_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockip_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockip',
                'db_table': 'BjRI3yQGhisBCfnZ',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('Type', models.CharField(max_length=50, verbose_name='Type')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(blank=True, help_text='Content', null=True, verbose_name='Content')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesslog_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesslog_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccessLog',
                'db_table': 'AbFQAh45sPZK86hd',
            },
        ),
    ]
