# Generated by Django 2.2 on 2021-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Question'),
        ),
    ]
