# Generated by Django 2.2 on 2021-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0002_auto_20210619_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockip',
            name='ip_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ip Level'),
        ),
        migrations.AddField(
            model_name='blockip',
            name='ip_option',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0, verbose_name='IP Option'),
        ),
    ]
