# Generated by Django 2.2 on 2023-03-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0051_auto_20230321_1843'),
        ('trade_master', '0003_auto_20210621_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('modified_on', models.DateTimeField(verbose_name='Modified On')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Userid', to='trade_admin_auth.User_Management', verbose_name='Username')),
            ],
            options={
                'verbose_name': 'LoginHistory',
                'db_table': 'Avfy3ZYuyC2l2BA',
            },
        ),
    ]
