# Generated by Django 2.2 on 2023-04-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0004_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Category')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'SupportCategory',
                'db_table': 'SCate721GFH27LOW22',
            },
        ),
        migrations.AddField(
            model_name='contactus',
            name='attachment',
            field=models.TextField(blank=True, help_text='ex : [a,b,1,2]', null=True, verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='support_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ticket Id'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='read_status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Opened'), (2, 'Closed'), (3, 'Cancelled'), (4, 'Re-opened')], default=0, verbose_name='Read Status'),
        ),
    ]
