# Generated by Django 2.2 on 2023-04-08 16:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0005_auto_20230408_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=50, verbose_name='Created by')),
                ('comment', ckeditor.fields.RichTextField(help_text='Comment', verbose_name='Comment')),
                ('attachment', models.TextField(blank=True, help_text='ex : [a,b,1,2]', null=True, verbose_name='attachment')),
                ('user_type', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0, verbose_name='User Type')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TicketId', to='trade_master.Contactus', verbose_name='TicketID')),
            ],
            options={
                'verbose_name': 'SupportTicket',
                'db_table': 'SupportN563gf8n2Ve',
            },
        ),
    ]
