# Generated by Django 2.2 on 2023-04-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0055_auto_20230408_1625'),
        ('trade_master', '0006_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contactus_User', to='trade_admin_auth.User_Management', verbose_name='User'),
        ),
    ]
