# Generated by Django 2.2 on 2023-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_master', '0007_contactus_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone1',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='read_status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Replied'), (2, 'Closed'), (3, 'Cancelled'), (4, 'Re-opened')], default=0, verbose_name='Read Status'),
        ),
    ]
