# Generated by Django 2.2 on 2023-07-28 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_master', '0008_auto_20230724_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=20, verbose_name='Module Code')),
                ('module_name', models.CharField(max_length=50, verbose_name='Module Name')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'MenuModules',
                'db_table': '21HbadiSPqTR4E0L',
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('access_permissions', models.IntegerField(blank=True, choices=[(0, 'NotAssign'), (1, 'Write'), (2, 'Read')], null=True, verbose_name='Access Permissions')),
                ('access_status', models.IntegerField(blank=True, choices=[(0, 'Access'), (1, 'Denied')], null=True, verbose_name='Access Status')),
                ('access_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_master.MenuModule')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menupermission_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menupermission_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_menupermissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MenuPermissions',
                'db_table': '12s8VH6oGW3Zh7F0',
            },
        ),
    ]
