# Generated by Django 2.2 on 2023-08-01 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_master', '0009_menumodule_menupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconMenuModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_module_name', models.CharField(max_length=50, verbose_name='Icon Module Name')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
            ],
            options={
                'verbose_name': 'IconMenuModule',
                'db_table': '41HbadiSPqTRicon',
            },
        ),
        migrations.CreateModel(
            name='SubMenuModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_module_name', models.CharField(max_length=50, verbose_name='Sub Module Name')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('main_module_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menu_module', to='trade_master.MenuModule')),
            ],
            options={
                'verbose_name': 'SubMenuModules',
                'db_table': '31HbadiSPqTRSub',
            },
        ),
        migrations.CreateModel(
            name='SubMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('access_permissions', models.IntegerField(blank=True, choices=[(0, 'NotAssign'), (1, 'Write'), (2, 'Read')], null=True, verbose_name='Access Permissions')),
                ('access_status', models.IntegerField(blank=True, choices=[(0, 'Access'), (1, 'Denied')], null=True, verbose_name='Access Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenupermission_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('main_access_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_access_modules', to='trade_master.MenuPermission')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenupermission_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('sub_menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu_name', to='trade_master.SubMenuModule')),
                ('user_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_menupermissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubMenuPermissions',
                'db_table': '51s8VpermoGW3Zh7F0sub',
            },
        ),
        migrations.CreateModel(
            name='IconMenuPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('access_permissions', models.IntegerField(blank=True, choices=[(0, 'NotAssign'), (1, 'Write'), (2, 'Read')], null=True, verbose_name='Access Permissions')),
                ('access_status', models.IntegerField(blank=True, choices=[(0, 'Access'), (1, 'Denied')], null=True, verbose_name='Access Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iconmenupermission_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('icon_menu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_menu_name', to='trade_master.IconMenuModule')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iconmenupermission_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('submenu_access_modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu_access_modules', to='trade_master.SubMenuPermission')),
                ('user_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_user_menupermissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IconMenuPermissions',
                'db_table': '61s8Vperm3Zh7F0icon',
            },
        ),
        migrations.AddField(
            model_name='iconmenumodule',
            name='sub_module_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menu_module', to='trade_master.SubMenuModule'),
        ),
    ]
