# Generated by Django 2.2 on 2023-06-03 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internal_transfer_admin_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fees', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Reward Percent')),
                ('health_wallet', models.BooleanField(default=True)),
                ('referral_wallet', models.BooleanField(default=True)),
                ('stake_referral_wallet', models.BooleanField(default=False)),
                ('stake_withdraw_wallet', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('minimum_internal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Minimum Internal Transfer Amount(Health)')),
                ('maximum_internal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Maximum Internal Transfer Amount(Health)')),
                ('minimum_internal_referal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Minimum Internal Transfer Amount(Referral)')),
                ('maximum_internal_referal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Maximum Internal Transfer Amount(Refarral)')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Internal_Transfer_Admin_Management',
                'db_table': 'aUOX702n6UQNFnwE',
            },
        ),
        migrations.CreateModel(
            name='internal_transfer_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('from_wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='From Wallet')),
                ('to_wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='To Wallet')),
                ('actual_amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Actual Amount(USDT)')),
                ('fees', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fees(%)')),
                ('amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount(JW)')),
                ('status', models.IntegerField(choices=[(0, 'Completed'), (1, 'Pending')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Internal_Transfer_History',
                'db_table': 'tEKgX0xAVANhx8U3',
            },
        ),
        migrations.CreateModel(
            name='stake_claim_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('claim_amount_USDT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Claim Amount USDT')),
                ('claim_amount_JW', models.CharField(blank=True, max_length=50, null=True, verbose_name='Claim Amount JW')),
                ('Address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('Transaction_Hash', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Transaction Hash')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('Two_Fa', models.IntegerField(blank=True, null=True, verbose_name='Two FA OTP')),
                ('Wallet_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Wallet type')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Stake_Claim_Table',
                'db_table': 'Wwsv4AxWH4cko399',
            },
        ),
        migrations.CreateModel(
            name='stake_deposit_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('Amount_USDT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount USDT')),
                ('Amount_JW', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount JW')),
                ('Hash', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hash')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Success')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Stake_Deposit_Management',
                'db_table': 'StagX0xAVANhxDEP',
            },
        ),
        migrations.CreateModel(
            name='Stake_history_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('Amount_USDT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount USDT')),
                ('Amount_JW', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount JW')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('period', models.IntegerField(blank=True, verbose_name='Period')),
                ('maximum_reward', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Maximum Reward')),
                ('reward_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Reward Percent')),
                ('reward_per_month', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Reward Per Month')),
                ('reward_earned', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Rewards Earned')),
                ('reward_balance', models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Rewards Balance')),
                ('referral_status', models.IntegerField(blank=True, verbose_name='User Referral Status')),
                ('referral_level', models.IntegerField(blank=True, null=True, verbose_name=' User Maximum Referral Eligible Level')),
                ('claim_status', models.IntegerField(choices=[(0, 'Enable'), (1, 'Disable'), (2, 'Claimed')], default=1, verbose_name='Status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Stake_history_management',
                'db_table': 'StaHISAVANhxD100',
            },
        ),
        migrations.CreateModel(
            name='Stake_referral_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField(blank=True, default=0, null=True, verbose_name='Referral Levels')),
                ('self_stake_Amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Self Stake Amount (USDT)')),
                ('self_stake_Amount_range', models.IntegerField(blank=True, default=0, null=True, verbose_name='Self Stake Amount Range (USDT)')),
                ('first_level_stake', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='First Level Stake Reward (%)')),
                ('secound_level_stake', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='Second Level Stake Onwards Reward (%)')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Stake_referral_management',
                'db_table': 'StaREFAVANhxD200',
            },
        ),
        migrations.CreateModel(
            name='Stake_referral_reward_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('direct_referral_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Direct Referral User')),
                ('referral_reward_amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referral Reward Amount')),
                ('referral_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referral Level')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stake_Referral_Reward_Table',
                'db_table': 'nUo3wQ2IVVUq2oh7',
            },
        ),
        migrations.CreateModel(
            name='stake_reward_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='Reward Amount')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stake_Reward_History',
                'db_table': 'STA4AxWH4ckoREW',
            },
        ),
        migrations.CreateModel(
            name='stake_wallet_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('stake_Wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stake Wallet')),
                ('stake_withdraw_Wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stake Withdraw Wallet')),
                ('stake_Refferal_Wallet', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stake Refferal Wallet')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Staking_Wallet_Management',
                'db_table': '7qWVxWgylCRXqUdz',
            },
        ),
        migrations.CreateModel(
            name='staking_admin_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_period', models.IntegerField(blank=True, verbose_name='Stake Period')),
                ('reward_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Reward Percent')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Stake Status')),
                ('minimum_stake', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Min Stake Amount')),
                ('maximum_stake', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Max Stake Amount')),
                ('minimum_withdraw', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Min Withdraw Amount')),
                ('maximum_withdraw', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Max Withdraw Amount')),
                ('minimum_withdraw_referal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Min Withdraw Amount (Referral Wallet)')),
                ('maximum_withdraw_referal', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Max Withdraw Amount (Referral Wallet)')),
                ('referral_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Referral Status')),
                ('referral_level', models.IntegerField(blank=True, null=True, verbose_name='Maximum Referral Eligible Level')),
                ('withdraw_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Withdraw Status')),
                ('stake_withdraw_transaction_fee', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Withdraw Fee')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
            ],
            options={
                'verbose_name': 'Staking_Admin_Management',
                'db_table': 'KE4EfjPravJ6mH3g',
            },
        ),
    ]
