# Generated by Django 2.2 on 2023-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0001_initial_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='internal_transfer_admin_management',
            index=models.Index(fields=['status'], name='aUOX702n6UQ_status_7d8316_idx'),
        ),
        migrations.AddIndex(
            model_name='internal_transfer_history',
            index=models.Index(fields=['user'], name='tEKgX0xAVAN_user_545c15_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_claim_table',
            index=models.Index(fields=['user'], name='Wwsv4AxWH4c_user_6f759c_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_deposit_management',
            index=models.Index(fields=['user'], name='StagX0xAVAN_user_a2f1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_history_management',
            index=models.Index(fields=['user'], name='StaHISAVANh_user_bdc513_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_referral_management',
            index=models.Index(fields=['levels'], name='StaREFAVANh_levels_c8ac00_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_referral_reward_table',
            index=models.Index(fields=['user'], name='nUo3wQ2IVVU_user_225fae_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_reward_history',
            index=models.Index(fields=['user'], name='STA4AxWH4ck_user_58138f_idx'),
        ),
        migrations.AddIndex(
            model_name='stake_wallet_management',
            index=models.Index(fields=['user'], name='DqWVxWgylCR_user_4f1642_idx'),
        ),
        migrations.AddIndex(
            model_name='staking_admin_management',
            index=models.Index(fields=['status', 'withdraw_status'], name='KE4EfjPravJ_status_48453f_idx'),
        ),
    ]
