# Generated by Django 2.2 on 2023-06-07 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0002_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='stake_claim_reward_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('stake_Wallet_reward_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='stake Wallet Reward Amount')),
                ('stake_withdraw_Wallet_reward_amount', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='stake Withdraw Wallet Reward Amount')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stake_Reward_History',
                'db_table': 'STACLAIH4ckoREW',
            },
        ),
        migrations.AddIndex(
            model_name='stake_claim_reward_history',
            index=models.Index(fields=['user'], name='STACLAIH4ck_user_d050e3_idx'),
        ),
    ]
