# Generated by Django 2.2 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0003_auto_20230607_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='staking_admin_management',
            name='eligible_plan',
            field=models.IntegerField(default=0, verbose_name='Stake Eligible Plan'),
        ),
        migrations.AddField(
            model_name='staking_admin_management',
            name='stake_wallet_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Stake wallet claim(%)'),
        ),
        migrations.AddField(
            model_name='staking_admin_management',
            name='withdraw_wallet_percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Withdraw Wallet claim(%)'),
        ),
    ]
