# Generated by Django 2.2 on 2023-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0004_auto_20230607_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake_claim_reward_history',
            name='stake_Wallet_percentage',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='stake Wallet percentage'),
        ),
        migrations.AddField(
            model_name='stake_claim_reward_history',
            name='stake_amount',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='stake amount'),
        ),
        migrations.AddField(
            model_name='stake_claim_reward_history',
            name='stake_withdraw_Wallet_percentage',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=36, null=True, verbose_name='stake withdraw Wallet percentage'),
        ),
    ]
