# Generated by Django 2.2 on 2023-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0005_auto_20230608_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staking_admin_management',
            name='maximum_stake',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='Max Stake Amount'),
        ),
        migrations.AlterField(
            model_name='staking_admin_management',
            name='maximum_withdraw',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='Max Withdraw Amount'),
        ),
        migrations.AlterField(
            model_name='staking_admin_management',
            name='minimum_stake',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='Min Stake Amount'),
        ),
        migrations.AlterField(
            model_name='staking_admin_management',
            name='minimum_withdraw',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='Min Withdraw Amount'),
        ),
        migrations.AlterField(
            model_name='staking_admin_management',
            name='minimum_withdraw_referal',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True, verbose_name='Min Withdraw Amount (Referral Wallet)'),
        ),
    ]
