# Generated by Django 2.2 on 2023-07-03 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0006_auto_20230621_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stake_Monthly_Claim_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='User')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('stake_amount', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16, null=True, verbose_name='Stake Amount')),
                ('earned_stake_reward', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16, null=True, verbose_name='Earned Stake Reward Amount')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End date')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Stake_Monthly_Claim_History',
                'db_table': 'STAH4ckMONoREWCLAI',
            },
        ),
        migrations.AddField(
            model_name='stake_history_management',
            name='Total_reward_earned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Total Reward Earned'),
        ),
        migrations.AddField(
            model_name='stake_history_management',
            name='referral_reward_earned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Referral Rewards Earned'),
        ),
        migrations.AlterField(
            model_name='stake_history_management',
            name='reward_earned',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='Stake Rewards Earned'),
        ),
        migrations.AddIndex(
            model_name='stake_monthly_claim_history',
            index=models.Index(fields=['user'], name='STAH4ckMONo_user_bb7a47_idx'),
        ),
    ]
