# Generated by Django 2.2 on 2023-07-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0007_auto_20230703_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stake_monthly_claim_history',
            name='stake_amount',
        ),
        migrations.AddField(
            model_name='stake_monthly_claim_history',
            name='stake_history_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stake_id', to='Staking.Stake_history_management', verbose_name='Stake History Id'),
        ),
    ]
