# Generated by Django 2.2 on 2023-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0008_auto_20230703_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='staking_admin_management',
            name='withdraw_fees',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, verbose_name='Withdraw Fees'),
        ),
        migrations.AlterField(
            model_name='stake_monthly_claim_history',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Claimed')], default=0, verbose_name='Status'),
        ),
    ]
