# Generated by Django 2.2 on 2023-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staking', '0009_auto_20230703_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake_claim_table',
            name='original_USDT',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Original claim Amount USDT'),
        ),
    ]
