# Generated by Django 2.2 on 2021-08-26 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0007_auto_20210525_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of Birth in mm/dd/yyyy Format', null=True)),
                ('emailaddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('address1', models.CharField(max_length=100, verbose_name='Contact Address1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Address2')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('agree', models.BooleanField(default=False)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code')),
                ('phone1', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tradeuserprofile', verbose_name='Profile Picture')),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'SubAdmin'), (2, 'Tradeusers')], default=0, verbose_name='Role')),
                ('pattern_code', models.IntegerField(default=0, verbose_name='Pattern Code')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('twofa', models.BooleanField(default=False)),
                ('google_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Id')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Deactive'), (3, 'Cancelled')], default=0, verbose_name='Status')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_country', to='locations.Country', verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': "Admin Profile's",
                'db_table': 'AYLkV0WRrgK0R9qM',
            },
        ),
        migrations.CreateModel(
            name='AdminUser_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('activity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Activity')),
                ('browsername', models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser Name')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System')),
                ('devices', models.CharField(blank=True, max_length=50, null=True, verbose_name='Devices')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser_activity_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser_activity_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_user_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AdminUser Activity',
                'db_table': 'AWxn5AxwlScnvVij',
            },
        ),
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailaddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Address')),
                ('ip_address', models.GenericIPAddressField()),
                ('activity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Activity')),
                ('browsername', models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser Name')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System')),
                ('devices', models.CharField(blank=True, max_length=50, null=True, verbose_name='Devices')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DateTime')),
                ('failedcount', models.IntegerField(verbose_name='Failed Logins')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessattempt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Attempt',
                'db_table': 'AVyjW0gtKU25eYSY',
            },
        ),
        migrations.AddIndex(
            model_name='adminuser_profile',
            index=models.Index(fields=['gender', 'twofa', 'status'], name='AYLkV0WRrgK_gender_eb17d7_idx'),
        ),
        migrations.AddIndex(
            model_name='accessattempt',
            index=models.Index(fields=['user', 'failedcount', 'ip_address', 'datetime'], name='AVyjW0gtKU2_user_id_8692ca_idx'),
        ),
    ]
