# Generated by Django 2.2 on 2022-09-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_admin_auth', '0002_adminuser_profile_pattern_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Two_x_boost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('daily_min', models.IntegerField(blank=True, null=True, verbose_name='Daily Minutes')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_x_boost_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_x_boost_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Two X Boost',
                'db_table': 'BOOW0gtKU25eYST',
            },
        ),
        migrations.CreateModel(
            name='Steps_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('maxi_step', models.IntegerField(blank=True, null=True, verbose_name='Maximum Step Per Day')),
                ('step_value', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Per Step Coin Value')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_management_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_management_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Steps Management',
                'db_table': 'STEPW0gtKU25eYSY',
            },
        ),
        migrations.AddIndex(
            model_name='two_x_boost',
            index=models.Index(fields=['daily_min', 'status'], name='BOOW0gtKU25_daily_m_f2b694_idx'),
        ),
        migrations.AddIndex(
            model_name='steps_management',
            index=models.Index(fields=['maxi_step', 'step_value', 'status'], name='STEPW0gtKU2_maxi_st_96fa4a_idx'),
        ),
    ]
