# Generated by Django 2.2 on 2022-09-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_admin_auth', '0003_auto_20220906_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name')),
                ('Email', models.CharField(blank=True, max_length=100, null=True, verbose_name='User Email Address')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='User Phone Number')),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to='userprofile', verbose_name='User Profile Picture')),
                ('over_all_stepcount', models.IntegerField(blank=True, null=True, verbose_name='User Over All Step Count ')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Management',
                'db_table': 'USPzTPzfNdmGTlER',
            },
        ),
        migrations.CreateModel(
            name='Steps_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('steps', models.IntegerField(blank=True, null=True, verbose_name='User Steps')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_history_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_history_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Steps_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Steps History',
                'db_table': 'STPzTPzfNdmGTlEP',
            },
        ),
        migrations.AddIndex(
            model_name='user_management',
            index=models.Index(fields=['user', 'Email', 'status'], name='USPzTPzfNdm_user_2d4555_idx'),
        ),
        migrations.AddIndex(
            model_name='steps_history',
            index=models.Index(fields=['user', 'steps', 'status'], name='STPzTPzfNdm_user_id_3b5f63_idx'),
        ),
    ]
