# Generated by Django 2.2 on 2022-09-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0004_auto_20220907_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_management',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user_management',
            name='modified_by',
        ),
    ]
