# Generated by Django 2.2 on 2022-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0005_auto_20220907_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=1, verbose_name='Status'),
        ),
    ]
