# Generated by Django 2.2 on 2022-09-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0006_auto_20220907_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_otp', models.IntegerField(blank=True, null=True, verbose_name='Email Registration OTP')),
                ('phone_number_opt', models.IntegerField(blank=True, null=True, verbose_name='Phone Number Registration OTP')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_otp', to='trade_admin_auth.User_Management')),
            ],
            options={
                'verbose_name': 'Registration OTP',
                'db_table': 'OTPzTPzfNdmGTlER',
            },
        ),
        migrations.AddIndex(
            model_name='registration_otp',
            index=models.Index(fields=['user', 'status'], name='OTPzTPzfNdm_user_id_e6d35f_idx'),
        ),
    ]
