# Generated by Django 2.2 on 2022-09-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0007_auto_20220907_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_two_fa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secrete_key', models.CharField(blank=True, max_length=128, null=True)),
                ('user_totp', models.CharField(blank=True, max_length=128, null=True)),
                ('user_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=200)),
                ('user_htotp', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_admin_auth.User_Management')),
            ],
            options={
                'verbose_name': 'User Two Fa',
                'db_table': 'FAKJDFGHKDFH',
            },
        ),
    ]
