# Generated by Django 2.2 on 2022-09-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0008_user_two_fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps_history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Steps_history', to='trade_admin_auth.User_Management'),
        ),
    ]
