# Generated by Django 2.2 on 2022-09-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0009_auto_20220909_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps_history',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='steps_history',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='steps_history',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='steps_history',
            name='modified_on',
        ),
    ]
