# Generated by Django 2.2 on 2022-09-09 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0010_auto_20220909_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_history',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='steps_history',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
