# Generated by Django 2.2 on 2022-09-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0012_user_management_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='user_profile',
            field=models.CharField(blank=True, default='', max_length=126, null=True, verbose_name='user profile'),
        ),
    ]
