# Generated by Django 2.2 on 2022-09-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0013_auto_20220919_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='user_profile',
            field=models.CharField(blank=True, default='', max_length=400, null=True, verbose_name='user profile'),
        ),
    ]
