# Generated by Django 2.2 on 2022-09-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0014_auto_20220919_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='referal_code',
            field=models.CharField(blank=True, default='U926C0', max_length=50, null=True, verbose_name='referral Code'),
        ),
    ]


