# Generated by Django 2.2 on 2022-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0015_user_management_referal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='referal_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='referral Code'),
        ),
    ]
