# Generated by Django 2.2 on 2022-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0016_auto_20220921_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser_profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jsanwellness/', verbose_name='Profile Picture'),
        ),
    ]
