# Generated by Django 2.2 on 2022-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0017_auto_20220922_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='User_Device_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='User Device id'),
        ),
    ]
