# Generated by Django 2.2 on 2022-09-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0018_user_management_user_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='User_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='User Type'),
        ),
    ]
