# Generated by Django 2.2 on 2022-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0019_user_management_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='User_Verification_Status',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='User Verification Status'),
        ),
    ]
