# Generated by Django 2.2 on 2022-09-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0020_user_management_user_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='Activate_Status',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='User Activate Status'),
        ),
    ]
