# Generated by Django 2.2 on 2022-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0021_user_management_activate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='over_all_stepcount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='User Over All Step Count '),
        ),
    ]
