# Generated by Django 2.2 on 2022-09-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0022_auto_20220927_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='User_Target',
            field=models.CharField(blank=True, default='5000', max_length=200, null=True, verbose_name='User Target'),
        ),
    ]
