# Generated by Django 2.2 on 2022-10-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0023_user_management_user_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser_profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Deactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='registration_otp',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='steps_history',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='steps_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='two_x_boost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Deactive')], default=1, verbose_name='Status'),
        ),
    ]
