# Generated by Django 2.2 on 2022-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0024_auto_20221027_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='User_Device_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='User Device id'),
        ),
    ]
