# Generated by Django 2.2 on 2022-11-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0025_auto_20221104_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='plan',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Current Plan'),
        ),
    ]
