# Generated by Django 2.2 on 2022-11-05 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0026_user_management_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='plan_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='plan End Date'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='plan_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='plan Start Date'),
        ),
    ]
