# Generated by Django 2.2 on 2022-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0027_auto_20221105_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='referral_plan_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='referral_plan_status'),
        ),
    ]
