# Generated by Django 2.2 on 2022-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0028_user_management_referral_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='referral_plan_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='referral_plan_status'),
        ),
    ]
