# Generated by Django 2.2 on 2022-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0029_auto_20221107_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='Direct_referral_id',
            field=models.CharField(default='', max_length=50, verbose_name='Direct referral id'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Direct_referral_user_level',
            field=models.IntegerField(default=0, verbose_name='Direct Referral User Level'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Referral_Level',
            field=models.IntegerField(default=0, verbose_name='Referral Level'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Referral_id',
            field=models.CharField(default='', max_length=50, verbose_name='Referral id'),
        ),
    ]
