# Generated by Django 2.2 on 2022-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0030_auto_20221115_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='Direct_referral_id',
            field=models.CharField(default='', max_length=50, verbose_name='Red User'),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='Referral_Level',
            field=models.IntegerField(default=0, verbose_name='Under Level'),
        ),
    ]
