# Generated by Django 2.2 on 2022-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0031_auto_20221116_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='user_referral_eligible_level',
            field=models.IntegerField(default=0, verbose_name='User Referral Eligible Level'),
        ),
    ]
