# Generated by Django 2.2 on 2022-12-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0032_user_management_user_referral_eligible_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='withdraw_count',
            field=models.IntegerField(default=0, verbose_name='withdraw_count'),
        ),
    ]
