# Generated by Django 2.2 on 2022-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0033_user_management_withdraw_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_management',
            name='free_plan_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Free Plan Days'),
        ),
    ]
