# Generated by Django 2.2 on 2022-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0034_steps_management_free_plan_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='plan_validation',
            field=models.CharField(default='', max_length=100, verbose_name='Plan_Validation'),
        ),
    ]
