# Generated by Django 2.2 on 2022-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0035_user_management_plan_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser_profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Deactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Deactive')], default=1, verbose_name='Status'),
        ),
    ]
