# Generated by Django 2.2 on 2022-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0036_auto_20221219_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_history',
            name='Step_type',
            field=models.CharField(default='', max_length=100, verbose_name='Step_type'),
        ),
    ]
