# Generated by Django 2.2 on 2022-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0037_steps_history_step_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_history',
            name='reward_Status',
            field=models.IntegerField(default=0, verbose_name='Reward Status'),
        ),
    ]
