# Generated by Django 2.2 on 2022-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0038_steps_history_reward_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='user_profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Profile Picture'),
        ),
    ]
