# Generated by Django 2.2 on 2023-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0039_auto_20221230_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='App Version'),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='user_profile_pic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Type'),
        ),
    ]
