# Generated by Django 2.2 on 2023-01-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0040_auto_20230102_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_history',
            name='Step_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Step Discount'),
        ),
    ]
