# Generated by Django 2.2 on 2023-01-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0041_steps_history_step_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steps_history',
            name='Step_discount',
        ),
    ]
