# Generated by Django 2.2 on 2023-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0042_remove_steps_history_step_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_management',
            name='Step_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Step Discount'),
        ),
    ]
