# Generated by Django 2.2 on 2023-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0043_steps_management_step_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='Withdraw_max_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Withdraw max value'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Withdraw_min_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Withdraw min value'),
        ),
    ]
