# Generated by Django 2.2 on 2023-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0044_auto_20230218_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_management',
            name='Withdraw_max_value',
        ),
        migrations.RemoveField(
            model_name='user_management',
            name='Withdraw_min_value',
        ),
        migrations.AddField(
            model_name='user_management',
            name='Health_Withdraw_max_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Health Withdraw max value'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Health_Withdraw_min_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Health Withdraw min value'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Referral_Withdraw_max_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Referral Withdraw max value'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='Referral_Withdraw_min_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Referral Withdraw min value'),
        ),
    ]
