# Generated by Django 2.2 on 2023-02-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0045_auto_20230218_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='reward_step_amount',
            field=models.IntegerField(default=0, verbose_name='Direct Referral User Level'),
        ),
        migrations.AddField(
            model_name='user_management',
            name='reward_steps',
            field=models.IntegerField(default=0, verbose_name='Direct Referral User Level'),
        ),
    ]
