# Generated by Django 2.2 on 2023-02-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0046_auto_20230228_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='withdraw_status',
            field=models.IntegerField(default=0, verbose_name='withdraw status'),
        ),
    ]
