# Generated by Django 2.2 on 2023-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0047_user_management_withdraw_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='reward_step_amount',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='reward_step_amount'),
        ),
        migrations.AlterField(
            model_name='user_management',
            name='reward_steps',
            field=models.IntegerField(default=0, verbose_name='reward_steps'),
        ),
    ]
