# Generated by Django 2.2 on 2023-03-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0048_auto_20230228_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDateUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='User name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='User email')),
                ('plan_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan name')),
                ('planstart_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan start Date')),
                ('planend_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan End Date')),
                ('plan_updated_end_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Updated End Date')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PlanDateUpdateHistory',
                'db_table': 'HJdLcHNlnKz0',
            },
        ),
    ]
