# Generated by Django 2.2 on 2023-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0049_plandateupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='Two_X_Boost_status',
            field=models.IntegerField(default=0, verbose_name='Two X Boost status'),
        ),
    ]
