# Generated by Django 2.2 on 2023-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0050_user_management_two_x_boost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='Two_X_Boost_status',
            field=models.IntegerField(default=1, verbose_name='Two X Boost status'),
        ),
    ]
