# Generated by Django 2.2 on 2023-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0051_auto_20230321_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawSendHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='User')),
                ('claim_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Claim Amount')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='User Address')),
                ('Transaction_Hash', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='TransactionHash')),
                ('send_status', models.IntegerField(choices=[(0, 'Active'), (1, 'Completed'), (2, 'Cancelled'), (3, 'Pending')], default=3, verbose_name='Send Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WithdrawSendHistory',
                'db_table': 'VVGrKxGkFL8yghB',
            },
        ),
        migrations.RemoveField(
            model_name='withdrawsendhistory',
            name='address',
        ),
        migrations.AddField(
            model_name='withdrawsendhistory',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='withdrawsendhistory',
            name='from_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='From Address'),
        ),
        migrations.AddField(
            model_name='withdrawsendhistory',
            name='to_address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='To Address'),
        ),
        migrations.AlterField(
            model_name='withdrawsendhistory',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
