# Generated by Django 2.2 on 2023-03-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0052_auto_20230320_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number'),
        ),
    ]
