# Generated by Django 2.2 on 2023-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0053_user_management_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number'),
        ),
    ]
