# Generated by Django 2.2 on 2023-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0054_auto_20230408_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_management',
            name='withdraw_count',
            field=models.IntegerField(default=2, verbose_name='withdraw_count'),
        ),
    ]
