# Generated by Django 2.2 on 2023-04-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0055_auto_20230408_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_management',
            name='Step_counter_Discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Step counter Discount percentage'),
        ),
        migrations.AlterField(
            model_name='steps_management',
            name='Step_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Google fit Discount percentage'),
        ),
    ]
