# Generated by Django 2.2 on 2023-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0056_auto_20230413_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps_management',
            name='plan_active_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='plan active status'),
        ),
    ]
