# Generated by Django 2.2 on 2023-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0057_steps_management_plan_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps_management',
            name='Step_counter_Discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Step counter (Add percentage %)'),
        ),
        migrations.AlterField(
            model_name='steps_management',
            name='Step_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Google fit (Discount percentage %)'),
        ),
    ]
