# Generated by Django 2.2 on 2023-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0058_auto_20230418_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_management',
            name='user_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User_info'),
        ),
    ]
