# Generated by Django 2.2 on 2023-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0059_user_management_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='front_page_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Front_user_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Front Page User Count')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'frontpagemanagement',
                'db_table': 'FRONKxGkFL8yMAN',
            },
        ),
    ]
