# Generated by Django 2.2 on 2023-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0060_front_page_management'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user_management',
            index=models.Index(fields=['user', 'user_name', 'Email', 'status'], name='USPzTPzfNdm_user_e97db5_idx'),
        ),
    ]
