# Generated by Django 2.2 on 2023-05-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0061_auto_20230518_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawsendhistory',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email', to='trade_admin_auth.User_Management', verbose_name='Email'),
        ),
    ]
