# Generated by Django 2.2 on 2022-09-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_admin_auth', '0008_user_two_fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Google_status', models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='disable', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_admin_auth.User_Management')),
            ],
            options={
                'verbose_name': 'Google Fitness',
                'db_table': 'FAYUJHGJDFGHFH',
            },
        ),
    ]
