# Generated by Django 2.2 on 2022-09-09 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trade_currency', '0005_auto_20210702_1917'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_admin_auth', '0008_user_two_fa'),
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCashWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactiontype', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Investment'), (3, 'DailyInvestment'), (4, 'Referral'), (5, 'Ranking'), (6, 'Transfer')], default=0, verbose_name='Transaction Type')),
                ('balanceone', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Balance')),
                ('balancetwo', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Balance Two')),
                ('referalincome', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Referal Income Balance')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cashcurrency', to='trade_currency.TradeCurrency', verbose_name='Currency')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cashwallet', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserCashWallet',
                'verbose_name_plural': 'UserCashWallets',
                'db_table': 'WaLLkSDHT1M6Z0D6',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUserCashWallet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('transactiontype', models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Investment'), (3, 'DailyInvestment'), (4, 'Referral'), (5, 'Ranking'), (6, 'Transfer')], default=0, verbose_name='Transaction Type')),
                ('balanceone', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Balance')),
                ('balancetwo', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Balance Two')),
                ('referalincome', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Referal Income Balance')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_currency.TradeCurrency', verbose_name='Currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical UserCashWallet',
                'db_table': 'RDJuUjVODTg2TYqT',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='usercashwallet',
            index=models.Index(fields=['userid', 'currency', 'status'], name='WaLLkSDHT1M_userid__5ccf9d_idx'),
        ),
    ]
