# Generated by Django 2.2 on 2022-09-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0011_auto_20220909_0953'),
        ('API', '0002_auto_20220909_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_2x_Boost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_step_count', models.IntegerField(blank=True, null=True, verbose_name='User Step Count')),
                ('reward_per_step', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Reward')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_2x_Boost', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User 2X Boost',
                'db_table': 'REwQpslShyIjGUWw',
            },
        ),
        migrations.AddIndex(
            model_name='user_2x_boost',
            index=models.Index(fields=['userid', 'user_step_count', 'status'], name='REwQpslShyI_userid__b0b515_idx'),
        ),
    ]
