# Generated by Django 2.2 on 2022-09-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0011_auto_20220909_0953'),
        ('API', '0003_auto_20220913_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount')),
                ('Address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address')),
                ('Two_Fa', models.IntegerField(blank=True, null=True, verbose_name='Two FA OTP')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Withdraw', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdraw Request',
                'db_table': 'WITHALLkpbdzRGLQ',
            },
        ),
    ]
