# Generated by Django 2.2 on 2022-09-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status'),
        ),
    ]
