# Generated by Django 2.2 on 2022-09-19 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0014_auto_20220919_1128'),
        ('API', '0005_withdraw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount')),
                ('From_Address', models.CharField(blank=True, max_length=50, null=True, verbose_name='From Address')),
                ('To_Address', models.CharField(blank=True, max_length=50, null=True, verbose_name='To Address')),
                ('Transaction_Hash', models.CharField(blank=True, max_length=200, null=True, verbose_name='Transaction Hash')),
                ('status', models.CharField(blank=True, default='Success', max_length=50, null=True, verbose_name='To Address')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Withdraw_history', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Withdraw History',
                'db_table': 'HISSWITHkpbdzR',
            },
        ),
    ]
