# Generated by Django 2.2 on 2022-09-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_admin_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='market_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Price')),
            ],
            options={
                'verbose_name': 'Market Price',
                'db_table': 'MarITHkpbdREL',
            },
        ),
    ]
