# Generated by Django 2.2 on 2022-09-21 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0010_market_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_referral_code',
            options={'verbose_name': 'Admin Referral Code'},
        ),
        migrations.CreateModel(
            name='Reward_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(blank=True, null=True, verbose_name='steps')),
                ('Reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward Token')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_History', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reward history',
                'db_table': 'HIsREwQpnlShyh',
            },
        ),
    ]
