# Generated by Django 2.2 on 2022-09-21 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20220921_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reward_History', to='trade_admin_auth.User_Management', verbose_name='User'),
        ),
    ]
