# Generated by Django 2.2 on 2022-09-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20220921_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reward', models.IntegerField(blank=True, null=True, verbose_name='Referral Reward')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'db_table': 'ReFREWU25eYSY',
            },
        ),
    ]
