# Generated by Django 2.2 on 2022-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_referral_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_reward_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referral ID')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Reward History',
                'db_table': 'HIDReFREWU0eY9SY',
            },
        ),
    ]
