# Generated by Django 2.2 on 2022-09-22 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0017_auto_20220922_1046'),
        ('API', '0014_referral_reward_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_reward_history',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Referral_reward_History', to='trade_admin_auth.User_Management', verbose_name='User'),
        ),
    ]
