# Generated by Django 2.2 on 2022-09-24 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0020_user_management_user_verification_status'),
        ('API', '0015_referral_reward_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete_Account_Reason_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delete Reason')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Delete_Account_Reason_Management', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Delete Account Reason Management',
                'db_table': 'DELACREREkUu766',
            },
        ),
        migrations.CreateModel(
            name='Delete_Account_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delete_Account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Delete Account')),
                ('reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Delete_Account_Management', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Delete Account Management',
                'db_table': 'DELACCFREkU0e676',
            },
        ),
    ]
