# Generated by Django 2.2 on 2022-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_delete_account_management_delete_account_reason_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delete_account_reason_management',
            name='user',
        ),
    ]
