# Generated by Django 2.2 on 2022-09-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_remove_delete_account_reason_management_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward_history',
            name='reward_status',
            field=models.CharField(blank=True, default='step_reward', max_length=50, null=True, verbose_name='Reward Token'),
        ),
    ]
