# Generated by Django 2.2 on 2022-09-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0023_user_management_user_target'),
        ('API', '0018_reward_history_reward_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_profit', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Profit')),
                ('Profit_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Profit type')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancelled')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Admin_Profit', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Profit',
                'db_table': 'ADPROgvfd4yu89',
            },
        ),
    ]
