# Generated by Django 2.2 on 2022-09-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0019_admin_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_history',
            name='withdraw_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_id', to='API.Withdraw', verbose_name='Withdraw'),
        ),
    ]
