# Generated by Django 2.2 on 2022-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0020_withdraw_history_withdraw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='Transaction_Hash',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Transaction Hash'),
        ),
    ]
