# Generated by Django 2.2 on 2022-10-14 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_withdraw_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_fitness',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='withdraw_history',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='withdraw_history',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
