# Generated by Django 2.2 on 2022-10-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0022_auto_20221014_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='admin_referral_code',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='delete_account_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='delete_account_reason_management',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalusercashwallet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='referral_code',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='referral_reward',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user_2x_boost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='usercashwallet',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
    ]
