# Generated by Django 2.2 on 2022-10-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0024_auto_20221027_1747'),
        ('API', '0023_auto_20221027_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address line 1')),
                ('Address_line_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address line 2')),
                ('Country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('State', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pin Code')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='User_address', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Profit',
                'db_table': 'UserOgvfADDyu89',
            },
        ),
    ]
