# Generated by Django 2.2 on 2022-10-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='status',
            field=models.IntegerField(choices=[(0, 'Selected'), (1, 'Not Selected')], default=1, verbose_name='Address Status'),
        ),
    ]
