# Generated by Django 2.2 on 2022-10-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0025_user_address_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='name'),
        ),
    ]
