# Generated by Django 2.2 on 2022-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_user_address_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=1, verbose_name='Address Status')),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='plan name')),
                ('plan_amount', models.IntegerField(blank=True, choices=[(0, 'Monthly'), (1, 'Quarterly'), (2, 'Annual')], default=1, null=True, verbose_name='plan amount status')),
                ('Min_step_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Min step count')),
                ('Max_step_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Max step count')),
                ('reward_amount', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='reward_amount')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'plan',
                'db_table': 'pUDmgt5FK2',
            },
        ),
        migrations.AlterModelOptions(
            name='user_address',
            options={'verbose_name': 'User address'},
        ),
    ]
