# Generated by Django 2.2 on 2022-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0027_auto_20221101_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='referral_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('commission_amount', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='commission amount')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'referral level',
                'db_table': 'REFLEVROgvfd4yu89',
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='Max_step_count',
            field=models.IntegerField(default=0, verbose_name='Max step count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Min_step_count',
            field=models.IntegerField(default=0, verbose_name='Min step count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_amount',
            field=models.IntegerField(choices=[(0, 'Monthly'), (1, 'Quarterly'), (2, 'Annual')], default=1, verbose_name='plan amount status'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=50, verbose_name='plan name'),
        ),
    ]
