# Generated by Django 2.2 on 2022-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_auto_20221102_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(default='', max_length=50, verbose_name='plan name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')], default=1, verbose_name='Plan Type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='reward_amount'),
        ),
    ]
