# Generated by Django 2.2 on 2022-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_auto_20221104_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_purchase_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='plan purchase amount'),
        ),
    ]
