# Generated by Django 2.2 on 2022-11-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_plan_plan_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='referral_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='referral_plan_status'),
        ),
    ]
