# Generated by Django 2.2 on 2022-11-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0029_auto_20221107_1135'),
        ('API', '0031_plan_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='referral_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referral_id', models.IntegerField(default=0, verbose_name='Referral id')),
                ('Referral_Level', models.IntegerField(default=0, verbose_name='Referral Level')),
                ('Direct_referral_id', models.IntegerField(default=0, verbose_name='Direct referral id')),
                ('Direct_referral_user_level', models.IntegerField(default=0, verbose_name='Direct Referral User Level')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Referral Table',
                'db_table': 'rmDrx1hohP',
            },
        ),
    ]
