# Generated by Django 2.2 on 2022-11-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_referral_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_table',
            name='Direct_referral_id',
            field=models.CharField(default='', max_length=50, verbose_name='Direct referral id'),
        ),
        migrations.AlterField(
            model_name='referral_table',
            name='Referral_id',
            field=models.CharField(default='', max_length=50, verbose_name='Referral id'),
        ),
    ]
