# Generated by Django 2.2 on 2022-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0033_auto_20221114_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='maximum_credit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Maximum Amount'),
        ),
        migrations.AddField(
            model_name='plan',
            name='minimum_credit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Minimum Amount'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan Purchase Amount'),
        ),
    ]
