# Generated by Django 2.2 on 2022-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0034_auto_20221116_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusercashwallet',
            name='balancetwo',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Balance Two'),
        ),
        migrations.AlterField(
            model_name='historicalusercashwallet',
            name='referalincome',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Referal Income Balance'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='maximum_credit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Maximum Credit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='minimum_credit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Minimum Credit'),
        ),
        migrations.AlterField(
            model_name='usercashwallet',
            name='balancetwo',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Balance Two'),
        ),
        migrations.AlterField(
            model_name='usercashwallet',
            name='referalincome',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Referal Income Balance'),
        ),
    ]
