# Generated by Django 2.2 on 2022-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0035_auto_20221118_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_history',
            name='Wallet_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Wallet type'),
        ),
    ]
