# Generated by Django 2.2 on 2022-11-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_withdraw_history_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='Wallet_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Wallet type'),
        ),
    ]
