# Generated by Django 2.2 on 2022-11-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0037_withdraw_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_level',
            name='referral_level_id',
            field=models.IntegerField(default=0, verbose_name='Referral Level ID'),
        ),
    ]
