# Generated by Django 2.2 on 2022-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0038_referral_level_referral_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='reward amount'),
        ),
        migrations.AlterField(
            model_name='referral_reward',
            name='Reward',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Referral Reward'),
        ),
    ]
