# Generated by Django 2.2 on 2022-11-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0031_auto_20221116_1859'),
        ('API', '0039_auto_20221124_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internal_transfer_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_wallet', models.CharField(default='', max_length=50, verbose_name='from wallet')),
                ('to_wallet', models.CharField(default='', max_length=50, verbose_name='to wallet')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Amount')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Internal transfer history',
                'db_table': 'YtC9IYRsrB',
            },
        ),
    ]
