# Generated by Django 2.2 on 2022-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0040_internal_transfer_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Validity_days',
            field=models.IntegerField(default=0, verbose_name='Validity days'),
        ),
    ]
