# Generated by Django 2.2 on 2022-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0041_plan_validity_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_contract_address', models.CharField(default='', max_length=200, verbose_name='token_contract_address')),
                ('Main_contract_address', models.CharField(default='', max_length=200, verbose_name='Main_contract_address')),
            ],
            options={
                'verbose_name': 'Contract Address',
                'db_table': 'CNq2d2Q5T1',
            },
        ),
    ]
