# Generated by Django 2.2 on 2022-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0042_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdraw_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdraw_limit', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='minimum_withdraw_limit')),
                ('maximum_withdraw_limit', models.DecimalField(decimal_places=8, max_digits=16, verbose_name='maximum_withdraw_limit')),
            ],
        ),
    ]
