# Generated by Django 2.2 on 2022-11-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0043_withdraw_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw_values',
            options={'verbose_name': 'withdraw values'},
        ),
        migrations.AlterModelTable(
            name='withdraw_values',
            table='w7Va44ARJN',
        ),
    ]
