# Generated by Django 2.2 on 2022-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0044_auto_20221130_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw_values',
            name='maximum_withdraw_limit',
        ),
        migrations.RemoveField(
            model_name='withdraw_values',
            name='minimum_withdraw_limit',
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Health_wallet_maximum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health_wallet_maximum_withdraw_limit'),
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Health_wallet_minimum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health_wallet_minimum_withdraw_limit'),
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Health_wallet_withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health_wallet_withdraw_fee'),
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Referral_wallet_maximum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral_wallet_maximum_withdraw_limit'),
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Referral_wallet_minimum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral_wallet_minimum_withdraw_limit'),
        ),
        migrations.AddField(
            model_name='withdraw_values',
            name='Referral_wallet_withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral_wallet_withdraw_fee'),
        ),
    ]
