# Generated by Django 2.2 on 2022-12-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0045_auto_20221202_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
    ]
