# Generated by Django 2.2 on 2022-12-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0046_plan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_level',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='API.plan', verbose_name='Plan'),
        ),
    ]
