# Generated by Django 2.2 on 2022-12-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0047_referral_level_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='referral_level_eligible',
            field=models.IntegerField(default=0, verbose_name='referral level eligible'),
        ),
    ]
