# Generated by Django 2.2 on 2022-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0048_plan_referral_level_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flush_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flush_minimum_wallet_amount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Minimum Wallet Amount')),
                ('management', models.IntegerField(choices=[(0, 'Auto'), (1, 'Manual')], default=1, verbose_name='Management')),
            ],
            options={
                'verbose_name': 'Flush Management',
                'db_table': 'FPGv8eQ482',
            },
        ),
    ]
