# Generated by Django 2.2 on 2022-12-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0049_flush_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_purchase_amount_annual',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan Purchase Amount Annual'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_purchase_amount_monthly',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan Purchase Amount Monthly'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_purchase_amount_quarterly',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan Purchase Amount Quarterly'),
        ),
    ]
