# Generated by Django 2.2 on 2022-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0050_auto_20221215_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_history',
            name='Reward',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='Reward Token'),
        ),
    ]
