# Generated by Django 2.2 on 2022-12-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0051_auto_20221219_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='reward per day'),
        ),
    ]
