# Generated by Django 2.2 on 2022-12-21 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0052_auto_20221221_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward_history',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
