# Generated by Django 2.2 on 2022-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0053_auto_20221221_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_level',
            name='referral_level_id',
            field=models.IntegerField(default=0, verbose_name='Referral Level Eligible'),
        ),
    ]
