# Generated by Django 2.2 on 2022-12-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0054_auto_20221223_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_purchase_amount_annual',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Amount/Annual'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_purchase_amount_monthly',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Amount/Monthly'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_purchase_amount_quarterly',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Amount/Quarterly'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='referral_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Referral Status'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=36, verbose_name='reward per day'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1, verbose_name='Plan Status'),
        ),
        migrations.AlterField(
            model_name='referral_level',
            name='commission_amount',
            field=models.DecimalField(decimal_places=8, max_digits=16, verbose_name='Referral Commission (%)'),
        ),
        migrations.AlterField(
            model_name='referral_level',
            name='referral_level_id',
            field=models.IntegerField(default=0, verbose_name='Level'),
        ),
    ]
