# Generated by Django 2.2 on 2022-12-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0038_steps_history_reward_status'),
        ('API', '0055_auto_20221226_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_purchase_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_amount', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='plan_purchase_amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('plan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_id', to='API.plan', verbose_name='plan_id')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='plan_purchase_history_user', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Plan Purchase History',
                'db_table': 'LKpr3XzfUq',
            },
        ),
    ]
