# Generated by Django 2.2 on 2022-12-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0056_plan_purchase_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Max_step_count',
            field=models.IntegerField(verbose_name='Max step count'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='Min_step_count',
            field=models.IntegerField(verbose_name='Min step count'),
        ),
    ]
