# Generated by Django 2.2 on 2022-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0057_auto_20221229_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_level',
            name='referral_level_id',
            field=models.IntegerField(verbose_name='Level'),
        ),
    ]
