# Generated by Django 2.2 on 2022-12-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_admin_auth', '0038_steps_history_reward_status'),
        ('API', '0058_auto_20221229_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase_history',
            name='user_wallet_type',
            field=models.CharField(default='', max_length=200, verbose_name='user_wallet_type'),
        ),
        migrations.CreateModel(
            name='wallet_flush_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_balanceone', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='wallet_balanceone')),
                ('Wallet_referral_income', models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Wallet_referral_income')),
                ('User_before_plan', models.CharField(default='', max_length=200, verbose_name='User_before_plan')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_flush_history_user', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'wallet flush history',
                'db_table': 'lKzCcRKoUK',
            },
        ),
    ]
