# Generated by Django 2.2 on 2023-01-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0059_auto_20221230_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_values',
            name='first_withdraw_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='first_withdraw_value'),
        ),
    ]
