# Generated by Django 2.2 on 2023-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0060_withdraw_values_first_withdraw_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw_values',
            name='Health_wallet_maximum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health wallet Maximum limit'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='Health_wallet_minimum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health wallet Min limit'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='Health_wallet_withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health wallet withdraw_fee'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='Referral_wallet_maximum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral wallet Max limit'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='Referral_wallet_minimum_withdraw_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral wallet Min limit'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='Referral_wallet_withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral wallet withdraw fee'),
        ),
        migrations.AlterField(
            model_name='withdraw_values',
            name='first_withdraw_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='First withdraw Value'),
        ),
    ]
