# Generated by Django 2.2 on 2023-01-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0061_auto_20230102_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral_level',
            name='plan',
        ),
    ]
