# Generated by Django 2.2 on 2023-01-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0062_remove_referral_level_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='Withdraw_JW',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Withdraw JW Amount'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='Withdraw_USDT',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Withdraw USDT Amount'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='Withdraw_fee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Withdraw Fee'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='Amount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='USDT Amount'),
        ),
    ]
