# Generated by Django 2.2 on 2023-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0063_auto_20230105_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Completed'), (2, 'Cancelled')], default=0, verbose_name='Status'),
        ),
    ]
