# Generated by Django 2.2 on 2023-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0064_auto_20230106_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='two_X_Boost_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Boost Status'),
        ),
    ]
