# Generated by Django 2.2 on 2023-01-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0065_plan_two_x_boost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='withdraw_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Withdraw Status'),
        ),
    ]
