# Generated by Django 2.2 on 2023-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0066_plan_withdraw_status'),
    ]

    

    operations = [
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_Level',
            field=models.IntegerField(default=0, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_Two_X_Boost_status',
            field=models.IntegerField(default=0, verbose_name='Min step count'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_Withdraw_status',
            field=models.IntegerField(default=0, verbose_name='Plan_Withdraw_status'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_maximum_reward',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan_maximum_reward'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_maximum_step',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan_maximum_step'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_minimum_step',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Plan_minimum_step'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='Plan_referral_status',
            field=models.IntegerField(default=0, verbose_name='Min step count'),
        ),
        migrations.AddField(
            model_name='plan_purchase_history',
            name='User_plan_validation',
            field=models.CharField(default='', max_length=200, verbose_name='User_plan_validation'),
        ),
    ]
