# Generated by Django 2.2 on 2023-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0067_auto_20230120_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase_history',
            name='buy_type',
            field=models.CharField(default='', max_length=200, verbose_name='Buy Type'),
        ),
    ]
