# Generated by Django 2.2 on 2023-02-08 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0068_plan_purchase_history_buy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
