# Generated by Django 2.2 on 2023-02-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0069_auto_20230208_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
