# Generated by Django 2.2 on 2023-02-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0070_auto_20230208_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Reward_step_value',
            field=models.IntegerField(default=0, verbose_name='Reward Step value'),
        ),
    ]
