# Generated by Django 2.2 on 2023-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0071_plan_reward_step_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase_history',
            name='plan_reward_step_val',
            field=models.IntegerField(default=0, verbose_name='Reward Step For Plan'),
        ),
    ]
