# Generated by Django 2.2 on 2023-02-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0072_plan_purchase_history_plan_reward_step_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='maximum_credit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='minimum_credit',
        ),
        migrations.AddField(
            model_name='plan',
            name='health_withdraw_maximum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Reward Wallet withdraw Maximum Limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='health_withdraw_minimum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Reward Wallet withdraw Minimum Limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='referral_withdraw_maximum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral Wallet withdraw Maximum Limit'),
        ),
        migrations.AddField(
            model_name='plan',
            name='referral_withdraw_minimum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral Wallet withdraw Minimum Limit'),
        ),
    ]
