# Generated by Django 2.2 on 2023-02-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0073_auto_20230218_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='plan reward amount'),
        ),
    ]
