# Generated by Django 2.2 on 2023-02-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0074_plan_plan_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Reward for Steps'),
        ),
    ]
