# Generated by Django 2.2 on 2023-02-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0075_auto_20230223_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='health_withdraw_maximum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health Wallet withdraw Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='health_withdraw_minimum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health Wallet withdraw Minimum Limit'),
        ),
    ]
