# Generated by Django 2.2 on 2023-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0076_auto_20230227_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_purchase_history',
            name='plan_per_reward_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='plan per reward amount'),
        ),
    ]
