# Generated by Django 2.2 on 2023-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0077_auto_20230303_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_purchase_wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Health_wallet_plan', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Health Wallet Plan buy Status')),
                ('Health_wallet_Withdraw', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Health Wallet Withdraw Status')),
                ('Referral_wallet_plan', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Referral Wallet Plan buy Status')),
                ('Referral_wallet_Withdraw', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Referral Wallet Withdraw Status')),
                ('Trust_wallet_plan', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Trust Wallet Plan buy Status')),
                ('Trust_wallet_Withdraw', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Trust Wallet Withdraw Status')),
            ],
            options={
                'verbose_name': 'Plan purchase wallet',
                'db_table': 'PPwr3XzfU7',
            },
        ),
    ]
