# Generated by Django 2.2 on 2023-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0078_auto_20230321_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Total_maximum_limit',
            field=models.IntegerField(default=0, verbose_name='Maximum Withdraw Limit Per Month'),
        ),
    ]
