# Generated by Django 2.2 on 2023-03-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0079_auto_20230323_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_values',
            name='Minimum_BNB_Balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Minimum BNB Balance'),
        ),
    ]
