# Generated by Django 2.2 on 2023-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0080_auto_20230329_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_notification_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_message', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Notification message')),
                ('Notification_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Notification Status')),
            ],
            options={
                'verbose_name': 'Admin Notification Message',
                'db_table': 'NOTr3XzfiFY',
            },
        ),
    ]
