# Generated by Django 2.2 on 2023-04-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0081_auto_20230407_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_notification_message',
            name='Google_fit_message',
            field=models.TextField(blank=True, null=True, verbose_name='Google fit Message'),
        ),
        migrations.AddField(
            model_name='admin_notification_message',
            name='Step_counter_message',
            field=models.TextField(blank=True, null=True, verbose_name='Step Counter Message'),
        ),
    ]
