# Generated by Django 2.2 on 2023-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0082_auto_20230410_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_price',
            name='API',
            field=models.IntegerField(blank=True, null=True, verbose_name='API to be Used'),
        ),
        migrations.AddField(
            model_name='market_price',
            name='status',
            field=models.IntegerField(choices=[(0, 'API'), (1, 'Manual')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='market_price',
            name='market_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API Updated Market Price'),
        ),
    ]
