# Generated by Django 2.2 on 2023-04-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0083_auto_20230418_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_price',
            name='market_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Market Price'),
        ),
    ]
