# Generated by Django 2.2 on 2023-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0084_auto_20230418_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_address',
            name='Stake_contract_Address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Stake_contract_address'),
        ),
    ]
