# Generated by Django 2.2 on 2023-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0085_auto_20230503_1111'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='admin_profit',
            index=models.Index(fields=['user'], name='ADPROgvfd4y_user_id_b4afc3_idx'),
        ),
        migrations.AddIndex(
            model_name='admin_referral_code',
            index=models.Index(fields=['user'], name='ADREFFITHkp_user_id_c38de7_idx'),
        ),
        migrations.AddIndex(
            model_name='delete_account_management',
            index=models.Index(fields=['user'], name='DELACCFREkU_user_id_e478cb_idx'),
        ),
        migrations.AddIndex(
            model_name='internal_transfer_history',
            index=models.Index(fields=['user_id'], name='YtC9IYRsrB_user_id_07d9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['user'], name='PINSWITHkpb_user_id_43641a_idx'),
        ),
        migrations.AddIndex(
            model_name='plan_purchase_history',
            index=models.Index(fields=['user'], name='LKpr3XzfUq_user_id_bfe23b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral_code',
            index=models.Index(fields=['user'], name='REFFITHkpbd_user_id_cca92c_idx'),
        ),
        migrations.AddIndex(
            model_name='referral_reward_history',
            index=models.Index(fields=['user'], name='HIDReFREWU0_user_id_160ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='referral_table',
            index=models.Index(fields=['user_id'], name='rmDrx1hohP_user_id_5c4396_idx'),
        ),
        migrations.AddIndex(
            model_name='reward_history',
            index=models.Index(fields=['user'], name='HIsREwQpnlS_user_id_23351a_idx'),
        ),
        migrations.AddIndex(
            model_name='user_address',
            index=models.Index(fields=['user'], name='UserOgvfADD_user_id_26132e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet_flush_history',
            index=models.Index(fields=['user'], name='lKzCcRKoUK_user_id_20cf24_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['userid'], name='WITHALLkpbd_userid__bacfe9_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw_history',
            index=models.Index(fields=['user_id'], name='HISSWITHkpb_user_id_ae9d75_idx'),
        ),
    ]
