# Generated by Django 2.2 on 2023-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0086_auto_20230518_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Total_maximum_limit',
            field=models.IntegerField(default=0, verbose_name='Maximum Withdraw/Transfer Limit Per Month'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='health_withdraw_maximum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health Wallet withdraw/Transfer Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='health_withdraw_minimum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Health Wallet withdraw/Transfer Minimum Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='referral_withdraw_maximum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral Wallet withdraw/Transfer Maximum Limit'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='referral_withdraw_minimum_limit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16, verbose_name='Referral Wallet withdraw/Transfer Minimum Limit'),
        ),
    ]
