# Generated by Django 2.2 on 2023-06-08 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0087_auto_20230607_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_address_trust_wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Address')),
                ('wallet_type', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='wallet_type')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified On')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_address_trust_wallet', to='trade_admin_auth.User_Management', verbose_name='User')),
            ],
            options={
                'verbose_name': 'user_address_trust_wallet',
                'db_table': 'USERWALLETXVhxDEP',
            },
        ),
    ]
