# Generated by Django 2.2 on 2023-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0088_auto_20230608_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUserCashWallet',
        ),
    ]
