# Generated by Django 2.2 on 2023-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0089_auto_20230621_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_level',
            name='second_level_commission_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Second Referral Commission (%)'),
        ),
    ]
