# Generated by Django 2.2 on 2020-12-29 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCurrency',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('currency_label', models.CharField(blank=True, max_length=20, null=True, verbose_name='Api Name')),
                ('currency_symbol', models.CharField(blank=True, max_length=20, null=True, verbose_name='Api Symbol')),
                ('currncytype', models.IntegerField(choices=[(0, 'Crypto'), (1, 'Fiat')], default=0, verbose_name='Currency Type')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('min_withdraw', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Minimum Withdraw Limit')),
                ('max_withdraw', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Maximum Withdraw Limit')),
                ('min_deposit', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Minimum Deposit Limit')),
                ('max_deposi', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Maximum Deposit Limit')),
                ('withdraw_feestype', models.IntegerField(choices=[(0, 'Percentage'), (1, 'Amount')], default=0, verbose_name='Withdraw Feestype')),
                ('withdraw_fees', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Withdraw Fees ')),
                ('currency_image', models.ImageField(blank=True, null=True, upload_to='currencyimage', verbose_name='Currency Image')),
                ('deposit_status', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, verbose_name='Deposit Status')),
                ('withdraw_status', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, verbose_name='Withdraw Status')),
                ('deposit_content', models.TextField(blank=True, null=True, verbose_name='Deposit Content')),
                ('withdraw_content', models.TextField(blank=True, null=True, verbose_name='Withdraw Content')),
                ('deposit_maintenance', models.TextField(blank=True, null=True, verbose_name='Deposit Maintenance')),
                ('withdraw_maintenance', models.TextField(blank=True, null=True, verbose_name='Withdraw Maintenance')),
                ('deposit_alert', models.TextField(blank=True, null=True, verbose_name='Deposit Alert')),
                ('withdraw_alert', models.TextField(blank=True, null=True, verbose_name='Withdraw Alert')),
                ('alert_deposit', models.BooleanField(default=False)),
                ('usd_value', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='USD Price ')),
                ('big_image', models.ImageField(blank=True, null=True, upload_to='bigcurrencyimage', verbose_name='Big Currency Image')),
                ('lend_status', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, verbose_name='Lending Status')),
                ('lending_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Minimum Lending ')),
                ('trans_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Minimum Transaction ')),
                ('lend_duration', models.IntegerField(verbose_name='Lend Duration')),
                ('lend_loanrate', models.IntegerField(verbose_name='Lend Rate')),
                ('balance_minimum', models.IntegerField(verbose_name='Balance Minimum')),
                ('depositcontent_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deposit Content 1')),
                ('depositcontent_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deposit Content 2')),
                ('depositcontent_three', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deposit Content 3')),
                ('withdrawcontent_one', models.CharField(blank=True, max_length=100, null=True, verbose_name='Withdraw Content 1')),
                ('withdrawcontent_two', models.CharField(blank=True, max_length=100, null=True, verbose_name='Withdraw Content 2')),
                ('countryname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Country Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradecurrency_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradecurrency_modified_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TradeCurrency',
                'verbose_name_plural': 'TradeCurrencys',
                'db_table': 'bUUEq7GKGRvh402t',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TradePairs',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair_name', models.CharField(max_length=20, verbose_name='Pair Name')),
                ('pair_url', models.CharField(max_length=20, verbose_name='Pair Url')),
                ('maker_fees', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Buy Limit Value (%)')),
                ('taker_fees', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Sell Limit Value (%)')),
                ('referal_fees', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Service Fee for Exchange(%)')),
                ('min_amount', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Minimum Amount ')),
                ('min_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='Minimum Price ')),
                ('max_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='maximum Price ')),
                ('margin_min_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='Margin Minimum Price ')),
                ('margin_max_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='Margin Maximum Price ')),
                ('margin_loan_duration', models.IntegerField(verbose_name='Margin Loan Duration')),
                ('margin_loan_rate', models.IntegerField(verbose_name='Margin Loan Rate')),
                ('last_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Last Price ')),
                ('change_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Buy Rate Value ')),
                ('volume_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=16, verbose_name='Sell Rate value')),
                ('high_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='24h High Price ')),
                ('low_price', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='24h Low Price ')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Cancel')], default=0, verbose_name='Status')),
                ('min_withdraw', models.DecimalField(decimal_places=8, default=0.0, max_digits=32, verbose_name='Minimum Withdraw ')),
                ('buylimit', models.IntegerField(choices=[(0, '+ (Plus)'), (1, '- (Minus)')], default=0, verbose_name='Buy Limit')),
                ('selllimit', models.IntegerField(choices=[(0, '+ (Plus)'), (1, '- (Minus)')], default=0, verbose_name='Sell Limit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradepairs_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('from_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_tradecurrency', to='trade_currency.TradeCurrency', verbose_name='From Symbol')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradepairs_modified_by_user', to=settings.AUTH_USER_MODEL)),
                ('two_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_tradecurrency', to='trade_currency.TradeCurrency', verbose_name='To Symbol')),
            ],
            options={
                'verbose_name': 'TradePairs',
                'verbose_name_plural': 'TradePairs',
                'db_table': 'eqBIRAHxs8eqW4Xu',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='tradepairs',
            index=models.Index(fields=['from_symbol', 'two_symbol', 'status'], name='eqBIRAHxs8e_from_sy_8cb550_idx'),
        ),
        migrations.AddIndex(
            model_name='tradecurrency',
            index=models.Index(fields=['name', 'status'], name='bUUEq7GKGRv_name_daf59e_idx'),
        ),
    ]
