# Generated by Django 2.2 on 2023-01-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_currency', '0005_auto_20210702_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecurrency',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tradepairs',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0, verbose_name='Status'),
        ),
    ]
